# 服务端地址
server: 127.0.0.1:8808
# ssl公钥
ssl-cert: ./cert.pem
# 内外部地址映射
# inner代表内网地址
# outer代表服务端绑定的地址
map:
  - inner: 127.0.0.1:8000
    outer: 0.0.0.0:9000
  - inner: 127.0.0.1:8000
    outer: 0.0.0.0:9100
